[package]
name = "dur"
version = "0.1.0"
authors = ["Lui, Timothy <eysew@gmail.com>"]
edition = "2024"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"

[dependencies]
x86_64 = "0.15.1"

[dependencies.lazy_static]
version = "1.5.0"
features = ["spin_no_std"]
