const SYSCALL_PREFIX: usize = 0x2000000;

/// A mapping of UArc syscalls to x86_64-macos syscalls.
/// `usize::MAX` means the syscall is unavailable for the platform.
pub const NRS: [usize; 420] = [
	1 + SYSCALL_PREFIX,
	3 + SYSCALL_PREFIX,
	4 + SYSCALL_PREFIX,
	6 + SYSCALL_PREFIX,
	189 + SYSCALL_PREFIX,
	199 + SYSCALL_PREFIX,
	59 + SYSCALL_PREFIX,
	20 + SYSCALL_PREFIX,
	167 + SYSCALL_PREFIX,
	23 + SYSCALL_PREFIX,
	24 + SYSCALL_PREFIX,
	26 + SYSCALL_PREFIX,
	36 + SYSCALL_PREFIX,
	95 + SYSCALL_PREFIX,
	37 + SYSCALL_PREFIX,
	41 + SYSCALL_PREFIX,
	51 + SYSCALL_PREFIX,
	54 + SYSCALL_PREFIX,
	92 + SYSCALL_PREFIX,
	82 + SYSCALL_PREFIX,
	151 + SYSCALL_PREFIX,
	60 + SYSCALL_PREFIX,
	61 + SYSCALL_PREFIX,
	39 + SYSCALL_PREFIX,
	147 + SYSCALL_PREFIX,
	195 + SYSCALL_PREFIX,
	123 + SYSCALL_PREFIX,
	117 + SYSCALL_PREFIX,
	116 + SYSCALL_PREFIX,
	122 + SYSCALL_PREFIX,
	85 + SYSCALL_PREFIX,
	55 + SYSCALL_PREFIX,
	74 + SYSCALL_PREFIX,
	73 + SYSCALL_PREFIX,
	200 + SYSCALL_PREFIX,
	201 + SYSCALL_PREFIX,
	124 + SYSCALL_PREFIX,
	100 + SYSCALL_PREFIX,
	96 + SYSCALL_PREFIX,
	157 + SYSCALL_PREFIX,
	158 + SYSCALL_PREFIX,
	86 + SYSCALL_PREFIX,
	83 + SYSCALL_PREFIX,
	7 + SYSCALL_PREFIX,
	165 + SYSCALL_PREFIX,
	12 + SYSCALL_PREFIX,
	13 + SYSCALL_PREFIX,
	131 + SYSCALL_PREFIX,
	65 + SYSCALL_PREFIX,
	120 + SYSCALL_PREFIX,
	121 + SYSCALL_PREFIX,
	310 + SYSCALL_PREFIX,
	203 + SYSCALL_PREFIX,
	204 + SYSCALL_PREFIX,
	324 + SYSCALL_PREFIX,
	325 + SYSCALL_PREFIX,
	53 + SYSCALL_PREFIX,
	337 + SYSCALL_PREFIX,
	181 + SYSCALL_PREFIX,
	47 + SYSCALL_PREFIX,
	25 + SYSCALL_PREFIX,
	43 + SYSCALL_PREFIX,
	126 + SYSCALL_PREFIX,
	127 + SYSCALL_PREFIX,
	79 + SYSCALL_PREFIX,
	80 + SYSCALL_PREFIX,
	78 + SYSCALL_PREFIX,
	75 + SYSCALL_PREFIX,
	97 + SYSCALL_PREFIX,
	135 + SYSCALL_PREFIX,
	104 + SYSCALL_PREFIX,
	98 + SYSCALL_PREFIX,
	106 + SYSCALL_PREFIX,
	118 + SYSCALL_PREFIX,
	105 + SYSCALL_PREFIX,
	32 + SYSCALL_PREFIX,
	31 + SYSCALL_PREFIX,
	133 + SYSCALL_PREFIX,
	28 + SYSCALL_PREFIX,
	29 + SYSCALL_PREFIX,
	27 + SYSCALL_PREFIX,
	134 + SYSCALL_PREFIX,
	255 + SYSCALL_PREFIX,
	254 + SYSCALL_PREFIX,
	265 + SYSCALL_PREFIX,
	263 + SYSCALL_PREFIX,
	262 + SYSCALL_PREFIX,
	264 + SYSCALL_PREFIX,
	260 + SYSCALL_PREFIX,
	261 + SYSCALL_PREFIX,
	259 + SYSCALL_PREFIX,
	258 + SYSCALL_PREFIX,
	usize::MAX,
	2 + SYSCALL_PREFIX,
	5 + SYSCALL_PREFIX,
	usize::MAX,
	9 + SYSCALL_PREFIX,
	10 + SYSCALL_PREFIX,
	14 + SYSCALL_PREFIX,
	15 + SYSCALL_PREFIX,
	usize::MAX,
	usize::MAX,
	usize::MAX,
	33 + SYSCALL_PREFIX,
	128 + SYSCALL_PREFIX,
	136 + SYSCALL_PREFIX,
	137 + SYSCALL_PREFIX,
	42 + SYSCALL_PREFIX,
	usize::MAX,
	usize::MAX,
	usize::MAX,
	usize::MAX,
	90 + SYSCALL_PREFIX,
	81 + SYSCALL_PREFIX,
	46 + SYSCALL_PREFIX,
	111 + SYSCALL_PREFIX,
	52 + SYSCALL_PREFIX,
	usize::MAX,
	57 + SYSCALL_PREFIX,
	58 + SYSCALL_PREFIX,
	usize::MAX,
	197 + SYSCALL_PREFIX,
	usize::MAX,
	188 + SYSCALL_PREFIX,
	190 + SYSCALL_PREFIX,
	usize::MAX,
	usize::MAX,
	usize::MAX,
	usize::MAX,
	184 + SYSCALL_PREFIX,
	usize::MAX,
	usize::MAX,
	usize::MAX,
	usize::MAX,
	48 + SYSCALL_PREFIX,
	usize::MAX,
	usize::MAX,
	usize::MAX,
	usize::MAX,
	usize::MAX,
	usize::MAX,
	usize::MAX,
	usize::MAX,
	usize::MAX,
	usize::MAX,
	93 + SYSCALL_PREFIX,
	187 + SYSCALL_PREFIX,
	usize::MAX,
	usize::MAX,
	usize::MAX,
	usize::MAX,
	usize::MAX,
	usize::MAX,
	usize::MAX,
	usize::MAX,
	usize::MAX,
	usize::MAX,
	usize::MAX,
	usize::MAX,
	230 + SYSCALL_PREFIX,
	usize::MAX,
	usize::MAX,
	usize::MAX,
	usize::MAX,
	usize::MAX,
	usize::MAX,
	usize::MAX,
	usize::MAX,
	usize::MAX,
	usize::MAX,
	usize::MAX,
	usize::MAX,
	usize::MAX,
	usize::MAX,
	66 + SYSCALL_PREFIX,
	194 + SYSCALL_PREFIX,
	16 + SYSCALL_PREFIX,
	364 + SYSCALL_PREFIX,
	usize::MAX,
	usize::MAX,
	usize::MAX,
	usize::MAX,
	usize::MAX,
	usize::MAX,
	usize::MAX,
	236 + SYSCALL_PREFIX,
	usize::MAX,
	237 + SYSCALL_PREFIX,
	234 + SYSCALL_PREFIX,
	usize::MAX,
	235 + SYSCALL_PREFIX,
	240 + SYSCALL_PREFIX,
	usize::MAX,
	241 + SYSCALL_PREFIX,
	238 + SYSCALL_PREFIX,
	usize::MAX,
	239 + SYSCALL_PREFIX,
	286 + SYSCALL_PREFIX,
	usize::MAX,
	usize::MAX,
	usize::MAX,
	usize::MAX,
	usize::MAX,
	usize::MAX,
	usize::MAX,
	usize::MAX,
	usize::MAX,
	usize::MAX,
	usize::MAX,
	usize::MAX,
	usize::MAX,
	usize::MAX,
	usize::MAX,
	usize::MAX,
	usize::MAX,
	usize::MAX,
	usize::MAX,
	usize::MAX,
	usize::MAX,
	usize::MAX,
	usize::MAX,
	usize::MAX,
	usize::MAX,
	345 + SYSCALL_PREFIX,
	346 + SYSCALL_PREFIX,
	usize::MAX,
	usize::MAX,
	usize::MAX,
	usize::MAX,
	usize::MAX,
	usize::MAX,
	usize::MAX,
	usize::MAX,
	usize::MAX,
	usize::MAX,
	usize::MAX,
	usize::MAX,
	usize::MAX,
	usize::MAX,
	173 + SYSCALL_PREFIX,
	usize::MAX,
	usize::MAX,
	usize::MAX,
	usize::MAX,
	usize::MAX,
	usize::MAX,
	usize::MAX,
	usize::MAX,
	usize::MAX,
	usize::MAX,
	usize::MAX,
	usize::MAX,
	usize::MAX,
	usize::MAX,
	usize::MAX,
	usize::MAX,
	usize::MAX,
	usize::MAX,
	usize::MAX,
	usize::MAX,
	usize::MAX,
	usize::MAX,
	usize::MAX,
	usize::MAX,
	usize::MAX,
	usize::MAX,
	usize::MAX,
	usize::MAX,
	usize::MAX,
	138 + SYSCALL_PREFIX,
	usize::MAX,
	usize::MAX,
	usize::MAX,
	usize::MAX,
	usize::MAX,
	usize::MAX,
	usize::MAX,
	usize::MAX,
	usize::MAX,
	usize::MAX,
	usize::MAX,
	usize::MAX,
	usize::MAX,
	usize::MAX,
	usize::MAX,
	usize::MAX,
	usize::MAX,
	usize::MAX,
	usize::MAX,
	usize::MAX,
	usize::MAX,
	usize::MAX,
	usize::MAX,
	usize::MAX,
	usize::MAX,
	usize::MAX,
	usize::MAX,
	usize::MAX,
	usize::MAX,
	usize::MAX,
	usize::MAX,
	usize::MAX,
	usize::MAX,
	usize::MAX,
	usize::MAX,
	usize::MAX,
	usize::MAX,
	usize::MAX,
	usize::MAX,
	usize::MAX,
	usize::MAX,
	30 + SYSCALL_PREFIX,
	usize::MAX,
	usize::MAX,
	usize::MAX,
	usize::MAX,
	usize::MAX,
	usize::MAX,
	usize::MAX,
	usize::MAX,
	usize::MAX,
	usize::MAX,
	usize::MAX,
	usize::MAX,
	usize::MAX,
	usize::MAX,
	usize::MAX,
	usize::MAX,
	usize::MAX,
	usize::MAX,
	usize::MAX,
	usize::MAX,
	usize::MAX,
	usize::MAX,
	usize::MAX,
	usize::MAX,
	usize::MAX,
	usize::MAX,
	usize::MAX,
	usize::MAX,
	usize::MAX,
	usize::MAX,
	usize::MAX,
	usize::MAX,
	usize::MAX,
	usize::MAX,
	usize::MAX,
	usize::MAX,
	usize::MAX,
	usize::MAX,
	usize::MAX,
	usize::MAX,
	usize::MAX,
	usize::MAX,
	usize::MAX,
	usize::MAX,
	usize::MAX,
	usize::MAX,
	usize::MAX,
	usize::MAX,
	usize::MAX,
	usize::MAX,
	usize::MAX,
	usize::MAX,
	usize::MAX,
	usize::MAX,
	usize::MAX,
	usize::MAX,
	usize::MAX,
	usize::MAX,
	44 + SYSCALL_PREFIX,
	usize::MAX,
	usize::MAX,
	usize::MAX,
	usize::MAX,
	usize::MAX,
	usize::MAX,
	usize::MAX,
	usize::MAX,
	usize::MAX,
	usize::MAX,
	usize::MAX,
	usize::MAX,
	usize::MAX,
	338 + SYSCALL_PREFIX,
	340 + SYSCALL_PREFIX,
	339 + SYSCALL_PREFIX,
	usize::MAX,
	usize::MAX,
	usize::MAX,
	usize::MAX,
	usize::MAX,
	usize::MAX,
	256 + SYSCALL_PREFIX,
	usize::MAX,
	usize::MAX,
	usize::MAX,
	usize::MAX,
	usize::MAX,
	usize::MAX,
	usize::MAX,
	usize::MAX,
	usize::MAX,
	usize::MAX,
	usize::MAX,
	usize::MAX,
	usize::MAX,
	usize::MAX,
	usize::MAX,
	usize::MAX,
	usize::MAX,
	usize::MAX,
	usize::MAX,
	usize::MAX,
	usize::MAX,
	usize::MAX,
	usize::MAX,
	usize::MAX,
	usize::MAX,
	usize::MAX,
];
